# .streamlit/secrets.toml

[smtp]
# Para Gmail, use smtp.gmail.com:587
servidor = "smtp.gmail.com" 
porta = 587
email_remetente = "no.reply.lcm.contabilidade@gmail.com"
# Importante: Use a Senha de Aplicativo (gsvy ocvl aafq bpze)
senha_app = "gsvyocvlaafqbpze"